"""
Validates that the error-injection pipeline actually introduced differences.

Reads ``dataset_modifications.csv`` for each errors-per-story value in
``ERRORS_PER_STORY_VALUES`` and reports:

1. How many rows have a genuinely different ``original_text`` vs ``modified_text``.
2. How many rows' ``modified_text`` is actually present in the corresponding
   chapter ``.txt`` file. A chapter can receive more than one injected error,
   so each chapter file is checked against every row that references it.
"""

import csv
import logging
from dataclasses import dataclass, field
from pathlib import Path

from . import text_selection
from .dataset_storage import DATASET_CSV_NAME, modified_books_dir_name, normalize_whitespace

logger = logging.getLogger(__name__)

# Errors-per-story values to validate; each must match a folder already
# generated by dataset_generation.py (modified_books_ai_<value>).
ERRORS_PER_STORY_VALUES = [15, 25, 65, 220]


@dataclass(frozen=True)
class CsvValidationReport:
    """Summary of how many CSV rows show a genuine original/modified difference."""

    dataset_name: str
    csv_path: Path
    total_rows: int
    different_rows: int

    @property
    def percent_different(self) -> float:
        if self.total_rows == 0:
            return 0.0
        return (self.different_rows / self.total_rows) * 100


def validate_csv(csv_path: Path) -> CsvValidationReport:
    """
    Check how many rows in `csv_path` have a truly different original/modified text.

    Args:
        csv_path: Path to a ``dataset_modifications.csv`` file.

    Returns:
        A :class:`CsvValidationReport` summarizing the results.

    Raises:
        FileNotFoundError: If `csv_path` does not exist.
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    total_rows = 0
    different_rows = 0
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            total_rows += 1
            if row["original_text"] != row["modified_text"]:
                different_rows += 1

    return CsvValidationReport(
        dataset_name=csv_path.parent.name,
        csv_path=csv_path,
        total_rows=total_rows,
        different_rows=different_rows,
    )


def _log_report(report: CsvValidationReport) -> None:
    """Log a human-readable summary of a validation report."""
    logger.info(
        "%s: %d total errors, %d truly different (%.1f%%)",
        report.dataset_name,
        report.total_rows,
        report.different_rows,
        report.percent_different,
    )


@dataclass(frozen=True)
class TextPresenceReport:
    """Summary of how many CSV rows' modified_text was found in the .txt files."""

    dataset_name: str
    total_rows: int
    found_rows: int
    missing: list[tuple[str, str]] = field(default_factory=list)  # (chapter, error_type)

    @property
    def percent_found(self) -> float:
        if self.total_rows == 0:
            return 0.0
        return (self.found_rows / self.total_rows) * 100


def validate_modifications_applied(
    csv_path: Path, modified_books_dir: Path
) -> TextPresenceReport:
    """
    Check that each row's modified_text is actually present in its chapter file.

    A chapter can receive more than one injected error, so multiple rows may
    reference the same chapter file; each file is only read once.

    Args:
        csv_path: Path to a ``dataset_modifications.csv`` file.
        modified_books_dir: The ``modified_books_ai_<N>`` directory the CSV
            belongs to, containing the chapter ``.txt`` files to check against.

    Returns:
        A :class:`TextPresenceReport` summarizing the results.

    Raises:
        FileNotFoundError: If `csv_path` does not exist.
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    chapter_content_cache: dict[str, str] = {}

    def _normalized_chapter_content(chapter: str) -> str:
        if chapter not in chapter_content_cache:
            chapter_path = modified_books_dir / chapter
            try:
                raw_content = chapter_path.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                logger.warning("Could not read '%s': %s", chapter_path, exc)
                raw_content = ""
            chapter_content_cache[chapter] = normalize_whitespace(raw_content)
        return chapter_content_cache[chapter]

    total_rows = 0
    found_rows = 0
    missing: list[tuple[str, str]] = []

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            total_rows += 1
            chapter_content = _normalized_chapter_content(row["chapter"])
            modified_text = normalize_whitespace(row["modified_text"])
            if modified_text and modified_text in chapter_content:
                found_rows += 1
            else:
                missing.append((row["chapter"], row["error_type"]))

    return TextPresenceReport(
        dataset_name=csv_path.parent.name,
        total_rows=total_rows,
        found_rows=found_rows,
        missing=missing,
    )


def _log_presence_report(report: TextPresenceReport) -> None:
    """Log a human-readable summary of a text-presence report."""
    logger.info(
        "%s: %d/%d modified texts found in .txt files (%.1f%%)",
        report.dataset_name,
        report.found_rows,
        report.total_rows,
        report.percent_found,
    )
    for chapter, error_type in report.missing:
        logger.warning("  Not found in file: %s (%s)", chapter, error_type)


def validate_all(
    errors_per_story_values: list[int], books_dir: Path | None = None
) -> list[CsvValidationReport]:
    """
    Validate the ``dataset_modifications.csv`` for every errors-per-story value given.

    Args:
        errors_per_story_values: The list of errors-per-story values to check,
            each corresponding to a ``modified_books_ai_<value>`` folder.
        books_dir: Optional override for the ``original_books`` directory,
            used to locate the sibling ``modified_books_ai_*`` folders.

    Returns:
        One :class:`CsvValidationReport` per value whose CSV file was found.
        Missing CSV files are logged as warnings and skipped.
    """
    base_dir = text_selection.resolve_books_dir(books_dir).parent

    reports: list[CsvValidationReport] = []
    for errors_per_story in errors_per_story_values:
        modified_books_dir = base_dir / modified_books_dir_name(errors_per_story)
        csv_path = modified_books_dir / DATASET_CSV_NAME
        try:
            report = validate_csv(csv_path)
        except FileNotFoundError as exc:
            logger.warning("%s", exc)
            continue
        _log_report(report)
        reports.append(report)

        presence_report = validate_modifications_applied(csv_path, modified_books_dir)
        _log_presence_report(presence_report)

    return reports


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    validate_all(ERRORS_PER_STORY_VALUES)


if __name__ == "__main__":
    main()
